//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DataPool
{
	private static Queue<string> htmlTxtList;

	public static void Push(string htmlText)
	{
		throw new System.NotImplementedException();
	}

	public static string Pop()
	{
		throw new System.NotImplementedException();
	}

}

