//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class HtmlParser : IParser
{
	public virtual List<Stock> stockList
	{
		get;
		set;
	}

	public virtual void ReadFromPool()
	{
		throw new System.NotImplementedException();
	}

	public virtual Stock ParseHtml(string htmlText)
	{
		throw new System.NotImplementedException();
	}

}

