//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PaserJobManager : IJobManager
{
	public virtual int TimerInterval
	{
		get;
		set;
	}

	public List<IParser> Parsers;

	public virtual void Run()
	{
		throw new System.NotImplementedException();
	}

	public virtual void InitiateJobs(int jobCount)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetupTimeInterval(int timeInterval)
	{
		throw new System.NotImplementedException();
	}

}

