//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Persistencer
{
	public const string sqlTemplate = default(string) /* TODO: specify a default. You can define this by setting the DefaultValue stereotype property of the attribute. */;

	public virtual string GenerateSQL(Stock stockItem)
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateIntoDB(List<Stock> stockList)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CleanDB()
	{
		throw new System.NotImplementedException();
	}

}

