//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ReaderManger : IJobManager
{
    public void Run()
    {
        throw new NotImplementedException();
    }

    public void InitiateJobs(int jobCount)
    {
        throw new NotImplementedException();
    }

    public void SetupTimeInterval(int timeInterval)
    {
        throw new NotImplementedException();
    }
}

