//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class URLManager
{
	public virtual string URLTemplate
	{
		get;
		set;
	}

	public virtual void PrepareURLPool()
	{
		throw new System.NotImplementedException();
	}

	public virtual string GenerateURL(string[] pars)
	{
		throw new System.NotImplementedException();
	}

}

