//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class URLPool
{
	private static Queue<string> URLs;

	public static string Pop()
	{
		throw new System.NotImplementedException();
	}

	public static void Push(string URL)
	{
		throw new System.NotImplementedException();
	}

}

