//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class WebReader : IReader
{
	public virtual string ReadHTML(string URL)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ReadIntoPool(string htmlText)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Run()
	{
		throw new System.NotImplementedException();
	}

}

