//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DataPool
{
    private static Queue<string> htmlTxtList = new Queue<string>();
    private static object lockObjForPop = new object();
    private static object lockObjForPush = new object();
    public const string ENDOFQUEUE = "END";

	public static void Push(string htmlText)
	{
        lock (lockObjForPush)
        {
            htmlTxtList.Enqueue(htmlText);
        }
	}

    public static bool IsEmpty() 
    {
        if (htmlTxtList.Count > 0)
            return false;
        else
            return true;
    }

	public static string Pop()
	{
        lock (lockObjForPop)
        {
            if (htmlTxtList.Count > 0)
                return htmlTxtList.Dequeue();
            else
                return ENDOFQUEUE;
        }
	}

}

