//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

public class PaserJobManager : IJobManager
{
	public virtual int TimerInterval
	{
		get;
		set;
	}


	public List<IParser> Parsers =new List<IParser>();

    public PaserJobManager() 
    {
        InitiateJobs(1);
    }

	public virtual void Run()
	{
        Thread.Sleep(TimerInterval);
        OutputHelper.Output("Start to build Stock Object form DataPool.");
        while (SyncContext.ThreadQ.Count > 0 || !DataPool.IsEmpty())
        {
            foreach (HtmlParser item in Parsers)
            {
                item.ReadFromPool();
            }

            //Thread.Sleep(TimerInterval);
        }
        OutputHelper.Output("Start to build Stock Object completed.");
        
	}

	public virtual void InitiateJobs(int jobCount)
	{
		while(jobCount>0)
        {
            Parsers.Add(new HtmlParser());
            jobCount--;
        }
	}

	public virtual void SetupTimeInterval(int timeInterval)
	{
        TimerInterval = timeInterval;
	}

}

