//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

public class ReaderJobManger : IJobManager
{
	public List<IReader> Readers=new List<IReader>();

    public ReaderJobManger() 
    {

        //if (Environment.ProcessorCount > 2)
        //{
        //    InitiateJobs(Environment.ProcessorCount - 1);
        //}
        //else {
        //    InitiateJobs(1);
        //}
        InitiateJobs(1);//only one webreader is supported now. if more webreader crated,program will be in dead loop
        ThreadPool.SetMaxThreads(100,50);
    }

	public virtual void Run()
	{
        foreach (WebReader item in Readers)
        {
            Task.Run(new Action(item.Run));
        }


	}

    public virtual void InitiateJobs(int jobCount)
	{
        while (jobCount > 0)
        {
            Readers.Add(new WebReader());
            jobCount--;
        }
	}

	public virtual void SetupTimeInterval(int timeInterval)
	{
		throw new System.NotImplementedException();
	}

}

