//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class StockHistory
{
	/// <summary>
	/// 交易日
	/// </summary>
	public virtual DateTime TransactionDate
	{
		get;
		set;
	}

	public virtual string StockCode
	{
		get;
		set;
	}

	/// <summary>
	/// 今开
	/// </summary>
	public virtual Double OpenPrice
	{
		get;
		set;
	}

	/// <summary>
	/// 最新
	/// </summary>
	public virtual Double LatestPrice
	{
		get;
		set;
	}

	/// <summary>
	/// 最高
	/// </summary>
	public virtual Double TodayHigh
	{
		get;
		set;
	}

	/// <summary>
	/// 最低
	/// </summary>
	public virtual Double TodayLow
	{
		get;
		set;
	}

	/// <summary>
	/// 成交额
	/// </summary>
	public virtual Double Value
	{
		get;
		set;
	}

	/// <summary>
	/// 成交量
	/// </summary>
	public virtual Double Volume
	{
		get;
		set;
	}

}

