//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class URLPool
{
    private static Queue<string> URLs=new Queue<string>();
    private static object lockObjForPop = new object();
    private static object lockObjForPush = new object();
    public const string ENDOFQUEUE = "END";
    public static event EventHandler PoolEmptyEvent;

    public static string Pop()
    {
        lock (lockObjForPop) 
        {
            if (URLs.Count > 0)
                return URLs.Dequeue();
            else
                if (PoolEmptyEvent != null) {
                    PoolEmptyEvent.BeginInvoke(null, null,null,null);
                    PoolEmptyEvent = null;
                }
                return ENDOFQUEUE;
        }
        
    }

    public static void Push(string URL)
    {
            URLs.Enqueue(URL);
    }

}

