//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;


public class WebReader : IReader
{
	public virtual string ReadHTML(string URL)
	{

        HttpWebRequest req = null;
        //WebResponse result = null;
        //string resultstring="";

        try
        {
            req = WebRequest.Create(URL) as HttpWebRequest;
            req.KeepAlive = false;//不建立持久性连接
            //req.Timeout = 5000;//连接网址的超时时间
            req.ReadWriteTimeout = 10000;//读取网址内容的超时时间
            //result = req.GetResponse();
            //Stream ReceiveStream = result.GetResponseStream();

            ////read the stream into a string
            //StreamReader sr = new StreamReader(ReceiveStream,Encoding.UTF8);
            
            //resultstring = sr.ReadToEnd();

            SyncContext.ThreadQ.Enqueue(Thread.CurrentThread.ManagedThreadId);
            req.BeginGetResponse(ProcessWebResponse, req);  

        }
        catch (Exception exp)
        {
            OutputHelper.Output("Request failed. Reason:");
            OutputHelper.Output(URL + ":" + exp.Message);
        }
        //finally
        //{
        //    if (result != null)
        //    {
        //        result.Close();
        //    }
            
        //}


        //return resultstring;
        return string.Empty;
	}

	public virtual void ReadIntoPool(string htmlText)
	{
        DataPool.Push(htmlText);
	}

    public virtual void ProcessWebResponse(IAsyncResult result)
    {
        //read the stream into a string
        //OutputHelper.Output("ProcessWebResponse Thread: " + Thread.CurrentThread.ManagedThreadId.ToString() + " Start to run!");
        WebRequest webrequest = (WebRequest)result.AsyncState;
        try
        {

            using (WebResponse webresponse = webrequest.EndGetResponse(result))
            {
                Stream ReceiveStream = webresponse.GetResponseStream();
                StreamReader sr = new StreamReader(ReceiveStream, Encoding.UTF8);
                string resultstring = sr.ReadToEnd();
                if (!string.IsNullOrEmpty(resultstring))
                    ReadIntoPool(resultstring);
                else
                    URLPool.Push(webrequest.RequestUri.ToString());
            }
        }
        catch (Exception ex)
        {

            OutputHelper.Output("ProcessWebResponse failed: " + ex.Message + ". URL" + webrequest.RequestUri.ToString());
            URLPool.Push(webrequest.RequestUri.ToString());
            //System.GC.Collect();//强制垃圾回收,并释放资源
        }
        finally {
            webrequest.Abort();
           

        }

        SyncContext.ThreadQ.Dequeue();

        //OutputHelper.Output("ProcessWebResponse completed.");
    }

	public virtual void Run()
	{
        string url;
        OutputHelper.Output("Thread of Reading URL: " + Thread.CurrentThread.ManagedThreadId.ToString() + " Start to run!");

        SyncContext.ThreadQ.Enqueue(Thread.CurrentThread.ManagedThreadId);

        while (true) 
        {
            //ReadIntoPool(ReadHTML(url));
            if (SyncContext.ThreadQ.Count >= 30) {
                Thread.Sleep(1000);
                continue;
            }
                

            if ((url = URLPool.Pop()) != URLPool.ENDOFQUEUE)
                ReadHTML(url);
            else if (SyncContext.ThreadQ.Count==1)
                break;
        }

        SyncContext.ThreadQ.Dequeue();

        OutputHelper.Output("Thread of Reading URL completed.");

	}

}

